/**
 * Portfolio Blueprint — single source of truth.
 * Independent of Puck, AI models, S3, and build infrastructure.
 */

export type NodeId = string;

export type NodeType =
  | 'section'
  | 'container'
  | 'heading'
  | 'text'
  | 'image'
  | 'video'
  | 'button'
  | 'component';

export type AssetId = string;

export interface Asset {
  id: AssetId;
  url: string;
  alt?: string;
  width?: number;
  height?: number;
}

export interface NodeLayout {
  display?: 'block' | 'flex' | 'grid';
  direction?: 'row' | 'column';
  columns?: number;
  gap?: string;
  alignment?: string;
  width?: string;
}

export interface NodeStyles {
  background?: string;
  color?: string;
  padding?: string;
  typography?: {
    fontFamily?: string;
    fontSize?: string;
    fontWeight?: string | number;
    letterSpacing?: string;
  };
}

export interface NodeAnimation {
  type?: string;
  duration?: string;
  trigger?: string;
}

export interface ResponsiveOverrides {
  tablet?: {
    layout?: Partial<NodeLayout>;
    styles?: Partial<NodeStyles>;
  };
  mobile?: {
    layout?: Partial<NodeLayout>;
    styles?: Partial<NodeStyles>;
  };
}

export interface BlueprintNode {
  id: NodeId;
  type: NodeType;
  /** Registry key, e.g. hero.editorial, about.image_left */
  component?: string;
  props?: Record<string, unknown>;
  layout?: NodeLayout;
  styles?: NodeStyles;
  animation?: NodeAnimation;
  responsive?: ResponsiveOverrides;
  children?: BlueprintNode[];
  metadata?: Record<string, unknown>;
}

export interface PortfolioBlueprint {
  id: string;
  name: string;
  /** Theme this portfolio was cloned from (never mutate the theme itself). */
  themeId?: string;
  /** Design tokens copied from the theme at clone time. */
  tokens?: DesignTokens;
  assets: Record<AssetId, Asset>;
  sections: BlueprintNode[];
  /** V2 custom components generated by Code AI (compiled at runtime). */
  customComponents?: Record<string, CustomComponentDefinition>;
}

/** Shared theme / portfolio design token model. */
export interface DesignTokens {
  colors: {
    ink: string;
    paper: string;
    accent: string;
    muted: string;
  };
  typography: {
    display: string;
    body: string;
  };
  spacing: {
    sectionY: string;
  };
  radius: string;
}

/** V2 AI-generated React section component (source stored on Blueprint). */
export interface CustomComponentDefinition {
  id: string;
  label: string;
  source: string;
  css: string;
  defaultProps: Record<string, unknown>;
  description?: string;
  createdAt: string;
}

/** Stable section component ids used in V1 registry (+ V2 custom.*). */
export type SectionComponentId =
  | 'hero.editorial'
  | 'hero.layered'
  | 'nav.centered'
  | 'about.image_left'
  | 'about.image_right'
  | 'work.categories'
  | 'feature.split'
  | 'services.row'
  | 'gallery.masonry'
  | 'gallery.grid'
  | 'footer.minimal'
  | `custom.${string}`;
